
'use client';

import React, { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Loader2, Volume2 } from 'lucide-react';
import type { SummarizePdfOutput } from '@/ai/flows/summarize-pdf';
import type { GenerateGlossaryOutput } from '@/ai/flows/glossary-flow';
import type { GenerateQuizOutput, QuizQuestion } from '@/ai/schemas/quiz';
import { ScrollArea } from './ui/scroll-area';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from './ui/accordion';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from './ui/card';
import { RadioGroup, RadioGroupItem } from './ui/radio-group';
import { Label } from './ui/label';
import { cn } from '@/lib/utils';
import ReactMarkdown from 'react-markdown';
import { QuizAttempt } from '@/lib/db';

export type AiDialogType = 'summary' | 'key-points' | 'glossary' | 'quiz';

type AiDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  type: AiDialogType;
  isLoading: boolean;
  summaryOutput: SummarizePdfOutput | null;
  glossaryOutput: GenerateGlossaryOutput | null;
  quizOutput: GenerateQuizOutput | null;
  quizAttempt: QuizAttempt | null;
  onQuizSubmit: (questions: QuizQuestion[], answers: Record<number, string>) => void;
  onPlayAudio: (text: string) => void;
};

const AiDialog: React.FC<AiDialogProps> = ({
  open,
  onOpenChange,
  type,
  isLoading,
  summaryOutput,
  glossaryOutput,
  quizOutput,
  quizAttempt,
  onQuizSubmit,
  onPlayAudio
}) => {

  const renderLoading = (text: string) => (
    <div className="flex items-center justify-center space-x-2 h-full p-8">
      <Loader2 className="animate-spin" />
      <span>{text}</span>
    </div>
  )

  const renderSummaryContent = () => (
    <>
      <DialogHeader>
        <DialogTitle>AI Analysis</DialogTitle>
        <DialogDescription>
          Here's a summary and key points generated by the AI based on the document's content.
        </DialogDescription>
      </DialogHeader>
      <Tabs defaultValue={type === 'key-points' ? 'key-points' : 'summary'} className="w-full pt-4">
        <TabsList className="grid w-full grid-cols-2">
          <TabsTrigger value="summary">Summary</TabsTrigger>
          <TabsTrigger value="key-points">Key Points</TabsTrigger>
        </TabsList>
        <ScrollArea className="h-96">
          <TabsContent value="summary" className="p-4">
              <div className="flex justify-between items-center mb-2">
                <h3 className="text-lg font-semibold">Summary</h3>
                <Button variant="ghost" size="icon" onClick={() => onPlayAudio(summaryOutput?.summary || '')} disabled={!summaryOutput?.summary}>
                    <Volume2 className="h-5 w-5" />
                </Button>
              </div>
            {isLoading ? renderLoading('Generating summary...') : (
              <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                {summaryOutput?.summary || 'No summary available.'}
              </p>
            )}
          </TabsContent>
          <TabsContent value="key-points" className="p-4">
            <div className="flex justify-between items-center mb-2">
                <h3 className="text-lg font-semibold">Key Points</h3>
                <Button variant="ghost" size="icon" onClick={() => onPlayAudio(summaryOutput?.keyPoints?.join('. ') || '')} disabled={!summaryOutput?.keyPoints}>
                    <Volume2 className="h-5 w-5" />
                </Button>
            </div>
            {isLoading ? renderLoading('Extracting key points...') : (
              <ul className="list-disc pl-5 space-y-2 text-sm text-muted-foreground">
                {summaryOutput?.keyPoints?.map((point, index) => (
                  <li key={index}>{point}</li>
                )) || <li>No key points available.</li>}
              </ul>
            )}
          </TabsContent>
        </ScrollArea>
      </Tabs>
    </>
  );

  const renderGlossaryContent = () => (
    <>
        <DialogHeader>
            <DialogTitle>Glossary</DialogTitle>
            <DialogDescription>Key terms and concepts identified from the document by the AI.</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-96 pr-4">
            {isLoading ? renderLoading('Creating glossary...') : (
                 <Accordion type="single" collapsible className="w-full">
                    {glossaryOutput?.glossary?.map((item, index) => (
                        <AccordionItem value={`item-${index}`} key={index}>
                            <AccordionTrigger>{item.term}</AccordionTrigger>
                            <AccordionContent>
                                <div className="flex justify-between items-start">
                                    <p className="flex-1 pr-4">{item.definition}</p>
                                    <Button variant="ghost" size="icon" onClick={() => onPlayAudio(item.definition)} disabled={!item.definition}>
                                        <Volume2 className="h-5 w-5" />
                                    </Button>
                                </div>
                            </AccordionContent>
                        </AccordionItem>
                    ))}
                </Accordion>
            )}
        </ScrollArea>
    </>
  );
  
  const QuizView: React.FC<{ questions: QuizQuestion[] }> = ({ questions }) => {
    const [answers, setAnswers] = useState<Record<number, string>>(quizAttempt?.answers || {});
    const [submitted, setSubmitted] = useState(!!quizAttempt);
  
    const handleAnswerChange = (questionIndex: number, value: string) => {
      setAnswers(prev => ({ ...prev, [questionIndex]: value }));
    };
  
    const handleSubmit = () => {
      onQuizSubmit(questions, answers);
      setSubmitted(true);
    };

    const getResultColor = (index: number, option?: string) => {
        if (!submitted) return '';
        const question = questions[index];
        const userAnswer = quizAttempt?.answers[index] || answers[index];
        const isCorrect = question.answer === userAnswer;
        
        if (option) { 
            if (option === question.answer) return 'text-green-700 font-bold';
            if (option === userAnswer && !isCorrect) return 'text-red-700 font-bold';
        } else {
            return isCorrect ? 'text-green-700' : 'text-red-700';
        }
        return '';
    }
  
    return (
      <div className="space-y-6">
        {questions.map((q, index) => (
          <Card key={index}>
            <CardHeader>
              <div className="flex justify-between items-center">
                <CardTitle>Question {index + 1}</CardTitle>
                 <Button variant="ghost" size="icon" onClick={() => onPlayAudio(q.question)} disabled={!q.question}>
                    <Volume2 className="h-5 w-5" />
                </Button>
              </div>
            </CardHeader>
            <CardContent className="space-y-4">
              <p>{q.question}</p>
              {q.type === 'multiple-choice' && (
                <RadioGroup 
                    onValueChange={(value) => handleAnswerChange(index, value)}
                    disabled={submitted}
                    value={answers[index]}
                >
                  {q.options?.map((option, i) => (
                    <div key={i} className="flex items-center space-x-2">
                      <RadioGroupItem value={option} id={`q${index}-o${i}`} />
                      <Label htmlFor={`q${index}-o${i}`} className={cn(getResultColor(index, option))}>
                        {option}
                      </Label>
                    </div>
                  ))}
                </RadioGroup>
              )}
              {q.type === 'true-false' && (
                 <RadioGroup 
                    onValueChange={(value) => handleAnswerChange(index, value)}
                    disabled={submitted}
                    value={answers[index]}
                >
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="True" id={`q${index}-true`} />
                      <Label htmlFor={`q${index}-true`} className={cn(getResultColor(index, "True"))}>True</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <RadioGroupItem value="False" id={`q${index}-false`} />
                      <Label htmlFor={`q${index}-false`} className={cn(getResultColor(index, "False"))}>False</Label>
                    </div>
                </RadioGroup>
              )}
              {submitted && (
                 <div className={cn("p-4 rounded-md text-sm bg-muted prose dark:prose-invert max-w-none", getResultColor(index))}>
                    <div className="flex justify-between items-start">
                        <div className="flex-1 pr-4">
                            <p className="font-bold">Correct Answer: {q.answer}</p>
                            <ReactMarkdown>{q.explanation}</ReactMarkdown>
                        </div>
                         <Button variant="ghost" size="icon" onClick={() => onPlayAudio(`Correct answer: ${q.answer}. ${q.explanation}`)} disabled={!q.explanation}>
                            <Volume2 className="h-5 w-5" />
                        </Button>
                    </div>
                 </div>
              )}
            </CardContent>
          </Card>
        ))}
        {!submitted && (
            <Button onClick={handleSubmit} className="w-full">Submit Answers</Button>
        )}
        {submitted && quizAttempt && (
            <Card>
                <CardHeader>
                     <div className="flex justify-between items-center">
                        <div>
                            <CardTitle>Quiz Results & Suggestions</CardTitle>
                            <CardDescription>Your Score: {quizAttempt.score.toFixed(0)}%</CardDescription>
                        </div>
                        <Button variant="ghost" size="icon" onClick={() => onPlayAudio(quizAttempt.suggestions)} disabled={!quizAttempt.suggestions}>
                            <Volume2 className="h-5 w-5" />
                        </Button>
                    </div>
                </CardHeader>
                <CardContent className="prose dark:prose-invert max-w-none">
                    <ReactMarkdown>{quizAttempt.suggestions}</ReactMarkdown>
                </CardContent>
            </Card>
        )}
      </div>
    );
  };
  
  const renderQuizContent = () => (
    <>
        <DialogHeader>
            <DialogTitle>AI-Generated Quiz</DialogTitle>
            <DialogDescription>Test your knowledge with these questions based on the document.</DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[32rem] pr-4 mt-4">
            {isLoading ? renderLoading('Generating your quiz...') : (
                (quizOutput?.quiz || quizAttempt?.questions) && <QuizView questions={quizOutput?.quiz || quizAttempt!.questions} />
            )}
        </ScrollArea>
    </>
  );

  const renderContent = () => {
    switch (type) {
        case 'summary':
        case 'key-points':
            return renderSummaryContent();
        case 'glossary':
            return renderGlossaryContent();
        case 'quiz':
            return renderQuizContent();
        default:
            return null;
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        {renderContent()}
      </DialogContent>
    </Dialog>
  );
};

export default AiDialog;
